from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="login"),
    path('register_user/', views.register_user, name="register_user"),
    path('logout/', views.logoutUser, name="logout"),
    path('users/', views.users, name="users"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('student_dashboard/', views.student_dashboard, name="student_dashboard"),
    path('categories/', views.categories, name="categories"),
    path('category/add', views.add_category, name="add_category"),
    path('category/edit/<str:id>', views.edit_category, name="edit_category"),
    path('category/delete/<str:id>', views.delete_category, name="delete_category"),
    path('authors/', views.authors, name="authors"),
    path('author/add/', views.add_author, name="add_author"),
    path('author/edit/<str:id>', views.edit_author, name="edit_author"),
    path('author/delete/<str:id>', views.delete_author, name="delete_author"),
    path('languages/', views.languages, name="languages"),
    path('language/add/', views.add_language, name="add_language"),
    path('language/edit/<str:id>', views.edit_language, name="edit_language"),
    path('language/delete/<str:id>', views.delete_language, name="delete_language"),
    path('book_document_types/', views.book_document_types, name="book_document_types"),
    path('book_document_type/add/', views.add_book_document_type, name="add_book_document_type"),
    path('book_document_type/edit/<str:id>', views.edit_book_document_type, name="edit_book_document_type"),
    path('book_document_type/delete/<str:id>', views.delete_book_document_type, name="delete_book_document_type"),
    path('books/', views.books, name="books"),
    path('book/add/', views.add_book, name="add_book"),
    path('book/edit/<str:id>', views.edit_book, name="edit_book"),
    path('book/delete/<str:id>', views.delete_book, name="delete_book"),
    path('issued_books/', views.issued_books, name="issued_books"),
    path('issued_book/add/', views.add_issued_book, name="add_issued_book"),
    path('issued_book/edit/<str:id>', views.edit_issued_book, name="edit_issued_book"),
    path('issued_book/delete/<str:id>', views.delete_issued_book, name="delete_issued_book"),

    path('borrowed_books/', views.borrowed_books, name="borrowed_books"),
]