# Generated by Django 4.0.4 on 2022-05-27 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0003_category_date_created_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
