# Generated by Django 4.0.4 on 2022-05-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0004_author_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
