# Generated by Django 4.0.4 on 2022-05-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0005_delete_user_delete_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDocumentAssetType',
            new_name='BookDocumentType',
        ),
    ]
