# Generated by Django 4.0.4 on 2022-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0006_rename_bookdocumentassettype_bookdocumenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=300),
        ),
    ]
