# Generated by Django 4.0.4 on 2022-07-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0007_remove_book_library_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Language',
            new_name='language',
        ),
    ]
