# Generated by Django 4.0.4 on 2022-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_library', '0009_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=300),
        ),
    ]
